src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_naissance = null;

    /**
     * @var Collection<int, Livre>
     */
    #[ORM\ManyToMany(targetEntity: Livre::class, mappedBy: 'auteur')]
    private Collection $livres;

    #[ORM\Column(length: 50)]
    private ?string $photos = null;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): static
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): static
    {
        if (!$this->livres->contains($livre)) {
            $this->livres->add($livre);
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): static
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }

    public function getPhotos(): ?string
    {
        return $this->photos;
    }

    public function setPhotos(string $photos): static
    {
        $this->photos = $photos;

        return $this;
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use App\Entity\Livre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_de_naissance', null, [
                'widget' => 'single_text',
            ])
            ->add('photos', FileType::class, [
                'label' => 'Choisissez votre photo',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Merci de mettre une image au format PNG ou JPEG.',
                    ])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }


}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/auteur')]
final class AuteurController extends AbstractController
{
    #[Route(name: 'app_auteur_index', methods: ['GET'])]
    public function index(AuteurRepository $auteurRepository): Response
    {
        return $this->render('auteur/index.html.twig', [
            'auteurs' => $auteurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_auteur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger,
    #[Autowire('%kernel.project_dir%/public/uploads/photo')] string $photodirectory

    ): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photoFile = $form->get('photos')->getData();
            if ($photoFile) {
                $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);

                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $auteur->getPrenom() . '_' . $safeFilename . '.' . $photoFile->guessExtension();

                try {
                    $photoFile->move($photodirectory, $newFilename);
                } catch (FileException $e) {
                    dump($e);
                }

                $auteur->setPhotos($newFilename);
            }
            $entityManager->persist($auteur);
            $entityManager->flush();

            return $this->redirectToRoute('app_auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_auteur_show', methods: ['GET'])]
    public function show(Auteur $auteur): Response
    {
        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_auteur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager, #[Autowire('%kernel.project_dir%/public/uploads/photo')] string $photodirectory, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $photoFile = $form->get('photos')->getData();

            if ($photoFile) {
                $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);

                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $auteur->getPrenom() . '_' . $safeFilename . '.' . $photoFile->guessExtension();

                try {
                    $photoFile->move($photodirectory, $newFilename);
                } catch (FileException $e) {

                }
                $auteur->setPhotos($newFilename);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        // Définir le chemin de la photo actuelle pour l'aperçu
        $photoPath = $auteur->getPhotos() ? '/uploads/photo/' . $auteur->getPhotos() : null;

        return $this->render('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form->createView(),
            'photoPath' => $photoPath,
        ]);
    }


    #[Route('/{id}', name: 'app_auteur_delete', methods: ['POST'])]
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$auteur->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($auteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_auteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/auteur/_delete_form.html.twig
<form method="post" action="{{ path('app_auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/auteur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/auteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Auteur{% endblock %}

{% block body %}
    <h1>Edit Auteur</h1>

    {{ include('auteur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_auteur_index') }}">back to list</a>

    {{ include('auteur/_delete_form.html.twig') }}
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur index{% endblock %}

{% block body %}
    <h1>Auteur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_de_naissance</th>
                <th>Photos</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for auteur in auteurs %}
            <tr>
                <td>{{ auteur.id }}</td>
                <td>{{ auteur.nom }}</td>
                <td>{{ auteur.prenom }}</td>
                <td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }}</td>
                <td><img src="{{ asset('uploads/photo/' ~ auteur.photos) }}" alt="Photo de {{ auteur.prenom }}" style="width: 200px; height: auto;"></td>
                <td>
                    <a href="{{ path('app_auteur_show', {'id': auteur.id}) }}">show</a>
                    <a href="{{ path('app_auteur_edit', {'id': auteur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_auteur_new') }}">Create new</a>
{% endblock %}

templates/auteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Auteur{% endblock %}

{% block body %}
    <h1>Create new Auteur</h1>

    {{ include('auteur/_form.html.twig') }}

    <a href="{{ path('app_auteur_index') }}">back to list</a>
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur{% endblock %}

{% block body %}
    <h1>Auteur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ auteur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ auteur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ auteur.prenom }}</td>
            </tr>
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Photos</th>
                <td><img src="{{ asset('uploads/photo/' ~ auteur.photos) }}" alt="Photo de {{ auteur.prenom }}" style="width: 200px; height: auto;"></td>

            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_auteur_index') }}">back to list</a>

    <a href="{{ path('app_auteur_edit', {'id': auteur.id}) }}">edit</a>


    {{ include('auteur/_delete_form.html.twig') }}
{% endblock %}